# Namespace for the application
apiVersion: v1
kind: Namespace
metadata:
  name: hw-13-namespace
---
# Deployment for MySQL Database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: hw-13-namespace
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        imagePullPolicy: Never
        env:
        # Set environment variables for database configuration
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "app_db"
        - name: MYSQL_USER
          value: "app_user"
        - name: MYSQL_PASSWORD
          value: "apppassword"
        ports:
        - containerPort: 3306
        volumeMounts:
        # Mount volume for persistent data storage
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        emptyDir: {}
---
# Service for MySQL Database
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: hw-13-namespace
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
# Deployment for Web Application Backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: hw-13-namespace
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: hw-10_web:latest
        imagePullPolicy: Never
        env:
        # Set environment variables for backend to connect to the database
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "app_user"
        - name: DB_PASSWORD
          value: "apppassword"
        - name: DB_NAME
          value: "app_db"
        ports:
        - containerPort: 8080
---
# Service for Backend
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: hw-13-namespace
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
# Deployment for Web Application Frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: hw-13-namespace
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: hw-10_web:latest
        imagePullPolicy: Never
        env:
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        ports:
        - containerPort: 80
        imagePullPolicy: Never
---
# Service for Frontend
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: hw-13-namespace
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      ##targetPort: 80
      targetPort: 5000
  type: NodePort
